stages:
- stage: Dev
  jobs:
  - job: D1
  - job: D2
    steps:
    - bash: echo "This is Dev D2"

- stage: QA
  jobs:
  - job: Q1
    steps:
      - bash: echo "This is QA"

- stage: Prod
  jobs:
  - job: P1
    steps:
    - bash: echo "This is Production"

- stage: Test
  jobs:
  - job: T1
    steps:
    - bash: echo "This is Test"

- stage: DeployUSA
  jobs:
  - job: DeployUS1
    steps:
    - bash: echo "This is DeployUS1"
  dependsOn: Test    # this stage runs after Test

- stage: DeployUSB
  jobs:
  - job: DeployUS2
    steps:
    - bash: echo "This is US2"
  dependsOn: Test    # this stage runs in parallel with DeployUS1, after Test

- stage: DeployEurope
  dependsOn: 
  - DeployUSA
  - DeployUSB
  jobs:
  - job: Europe
    steps:
    - bash: echo "This is Europe"
  - job: Sweden
    steps:
    - bash: echo "This is Sweden"