# specific branch build
trigger:
  branches:
    include:
    - master
    - releases/*
    - develop
    exclude:
    - releases/old*
stages:
- stage: Dev
  jobs:
  - job: D1
  - job: D2
    steps:
    - bash: echo "This is Dev"