# this has one implicit stage and one implicit job
pool:
  vmImage: 'ubuntu-latest'
steps:
- bash: echo "Hello world"

# this pipeline has one implicit stage
  jobs:
  - job: A
    steps:
  - bash: echo "A"

  - job: B
    steps:
    - bash: echo "B"