# specific branch build
trigger:
  branches:
    include:
    - master
    - releases-*
    - develop
    exclude:
    - releases/old*
stages:
- stage:
  jobs:
    - job: waitForValidation
      displayName: Wait for external validation
      pool: server
      timeoutInMinutes: 4320 # job times out in 3 days
      steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            example@exampletesting999.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'resume'
- stage: Dev
  jobs:
  - job: D1
  - job: D2
    steps:
    - bash: echo "This is Dev"